services:
  api:
    build:
      context: .
      target: production
    container_name: satus_api_prod
    env_file:
      - .prod.env
    depends_on:
      mongodb-prod:
        condition: service_healthy
    ports:
      - "3003:3000"
    restart: always
    networks:
      - prod_net

  mongodb-prod:
    image: mongo:7.0
    container_name: satus_mongo_prod
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER} #Ref a .stg.env
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD} #Ref a .stg.env
      MONGO_INITDB_DATABASE: satus_prod_db
    ports:
      - "27017:27017"
    volumes:
      - satus_prod_data:/data/db
    restart: always
    healthcheck:         #delay para que no explote nestjs!!
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - prod_net

volumes:
  satus_prod_data:

networks:
  prod_net:
