services:
  api:
    build: .
    container_name: satus_api_stg
    env_file:
      - .stg.env
    ports:
      - "3004:3000"
    depends_on:
      mongodb-stg:
        condition: service_healthy
    networks:
      - stg_net

  mongodb-stg:
    image: mongo:7.0
    container_name: satus_mongo_stg
    environment:
      # Sync con .stg.env
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_NAME}
    ports:
      - "27018:27017" 
    volumes:
      - satus_stg_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - stg_net

  mongo-express-stg:
    image: mongo-express:latest
    container_name: satus_mexpress_stg
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongodb-stg:27017/
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: root
    ports:
      - "8082:8081"
    depends_on:
      - mongodb-stg
    networks:
      - stg_net

volumes:
  satus_stg_data:

networks:
  stg_net:
